# Default values for servermanager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

nameOverride: ""
fullnameOverride: ""

lifo:
  repository:  lifo
  tag: 1.0
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 2
    memory: 10Gi
  limits:
    cpu: "4"
    memory: "10Gi"

ports:
  containerPort: 8080

health:
  readinessProbe:
    exec:
      command:
        - curl
        - -X GET
        - http://127.0.0.1:8080/lifo/pingRequest
    initialDelaySeconds: 120
    periodSeconds: 2
    failureThreshold: 20
  livenessProbe:
    exec:
      command:
        - curl
        - -X GET
        - http://127.0.0.1:8080/lifo/pingRequest
    initialDelaySeconds: 120
    periodSeconds: 2
    failureThreshold: 20

nodeSelector:
  env: lifo

service:
  type: NodePort
  tcpPortList:
    tomcate-port: 30208

secretData:
  db_url: 
  db_user: 
  db_pwd: 

hostPath:
  system: "/u01/k8s_storage/lifo/Services"

